### PR TITLE
Support copying the most recent item to the counter table

### PR DESCRIPTION
**Pull request by lpsinger**
This is #20 as a one-liner.

### CODE REVIEW

**Comment by dakota002** [comment]
How does this handle the case for circulars? How do you see this used for versioning? 

In the case of an update to a specific circular, what kind of config options would you have to pass into this to result in keeping the same circularId and bumping the version field?

**Comment by lpsinger** [comment]
> Are we assuming that we should run a script or something that will backfill all existing circulars with a `version: 1` property and populate the entire history table?

Correct.

> * In the current tests, on adding a new item to the table, the counter table will overwrite the saved item, and only keep a copy of the latest inserted item. Is this resolved if the targeted counter table uses a sort key as well?

I don't understand the question.

**Comment by dakota002** [comment]
> > * In the current tests, on adding a new item to the table, the counter table will overwrite the saved item, and only keep a copy of the latest inserted item. Is this resolved if the targeted counter table uses a sort key as well?
> 
> I don't understand the question.

How do you maintain the history when inserting new rows?
I added the following test locally to check what happens when multiple items are intentionally inserted to the table:


```ts
test('maintains history when new items are inserted', async () => {
  const initialID = 1
  const firstResult = await autoincrement.put({
    widgetName: 'runcible spoon',
  })
  expect(firstResult).toEqual(initialID)
  expect(await autoincrement.getLast()).toEqual(initialID)

  const secondResult = await autoincrement.put({
    widgetName: 'a new widget',
  })
  expect(secondResult).toBe(initialID + 1)
  const [widgetItems, autoincrementItems] = await Promise.all(
    ['widgets', 'autoincrement'].map(
      async (TableName) => (await doc.scan({ TableName })).Items
    )
  )
  expect(widgetItems).toEqual([
    { widgetID: 2, widgetName: 'a new widget' },
    { widgetID: 1, widgetName: 'runcible spoon' },
  ])
  expect(autoincrementItems).toEqual(
    counterTableCopyItem
      ? [
          {
            tableName: 'widgets',
            counter: 1,
            widgetName: 'runcible spoon',
          },
          {
            tableName: 'widgets',
            counter: 2,
            widgetName: 'a new widget',
          },
        ]
      : [
          {
            tableName: 'widgets',
            counter: 2,
          },
        ]
  )
})

```

Which fails with the following:
```
counterTableCopyItem=true › dynamoDBAutoIncrement › maintains history when new items are inserted

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 0

      Array [
        Object {
    -     "counter": 1,
    -     "tableName": "widgets",
    -     "widgetName": "runcible spoon",
    -   },
    -   Object {
          "counter": 2,
          "tableName": "widgets",
          "widgetName": "a new widget",
        },
      ]

      153 |           { widgetID: 1, widgetName: 'runcible spoon' },       
      154 |         ])
    > 155 |         expect(autoincrementItems).toEqual(
          |                                    ^
      156 |           counterTableCopyItem
      157 |             ? [
      158 |                 {

      at Object.<anonymous> (src/test.ts:155:36)
```

**Comment by lpsinger** [comment]
> How do you maintain the history when inserting new rows?

Do you mean: how do you maintain history when inserting new GCN Circulars (entirely new Circulars that don't have a previous version)?

**Comment by dakota002** [comment]
> > How do you maintain the history when inserting new rows?
> 
> Do you mean: how do you maintain history when inserting new GCN Circulars (entirely new Circulars that don't have a previous version)?

Yes

**Comment by lpsinger** [comment]
> > > How do you maintain the history when inserting new rows?
> > 
> > 
> > Do you mean: how do you maintain history when inserting new GCN Circulars (entirely new Circulars that don't have a previous version)?
> 
> Yes

Good point. I have to think about that.

**Comment by lpsinger** [comment]
Closing in favor of #20.

**Pull request closed without merging**
